# Generated by Django 4.2.4 on 2014-04-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftCarrierClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('displacement', models.FloatField()),
                ('length', models.FloatField()),
                ('beam', models.FloatField()),
                ('aircrats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftCarrier',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('hull_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('vessel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='Api.aircraftcarrierclass')),
            ],
        ),
    ]
