# Generated by Django 4.2.4 on 2014-04-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraftcarrierclass',
            old_name='aircrats',
            new_name='aircrafts',
        ),
    ]
