# Generated by Django 4.2.4 on 2014-04-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_rename_aircrats_aircraftcarrierclass_aircrafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftcarrierclass',
            name='beam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aircraftcarrierclass',
            name='displacement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aircraftcarrierclass',
            name='length',
            field=models.IntegerField(),
        ),
    ]
