# Generated by Django 4.2.4 on 2014-04-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_aircraftcarrierclass_beam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armament',
            fields=[
                ('arm_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('arm_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='aircraftcarrier',
            name='builder',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
    ]
