# Generated by Django 4.2.4 on 2014-04-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_armament_aircraftcarrier_builder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACClassArmament',
            fields=[
                ('aa_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('arm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.armament')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armament', to='Api.aircraftcarrierclass')),
            ],
        ),
    ]
