# Generated by Django 4.2.4 on 2014-04-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_acclassarmament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('builder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraftcarrier',
            name='builder',
        ),
    ]
